@echo off
REM ---------- SPRING VARIABLES PERMANENTES ----------
setx SPRING_APP_NAME GestorAPI
setx SPRING_DB_URL jdbc:mysql://localhost:3306/gestor_bd
setx SPRING_DB_USERNAME root
setx SPRING_DB_PASSWORD abc123.
setx SPRING_HIBERNATE_DDL update
setx SPRING_HIBERNATE_SHOW_SQL true
setx SPRING_JWT_SECRET IDKNguVNiihte61wmeWTNqAYpXKg2vGpw6iHxFbk7ivQxA1Y19SS+zE7Or1G9T/YqvoHTV048g7M+TuoFV8IMg==
setx SPRING_JWT_EXPIRATION 1440

setx SPRING_GOOGLE_CLIENT_ID  "ID"
setx SPRING_GOOGLE_CLIENT_SECRET  "KEY"
setx SPRING_GOOGLE_REDIRECT_URI http://localhost:8080/login/oauth2/code/google

setx SPRING_GITHUB_CLIENT_ID "ID"
setx SPRING_GITHUB_CLIENT_SECRET "KEY"
setx SPRING_GITHUB_REDIRECT_URI http://localhost:8080/login/oauth2/code/github

setx SPRING_CORS_ALLOWED_ORIGINS http://localhost:4200
setx SPRING_OAUTH2_REDIRECT_URI http://localhost:4200/oauth2/redirect
setx SPRING_PYTHON_SERVER_URL http://localhost:5000
setx SPRING_PYTHON_API_KEY CREAR_API_KEY
setx SPRING_UPLOAD_DIR C:/uploads/
setx SPRING_MAX_FILE_SIZE 5MB
setx SPRING_MAX_REQUEST_SIZE 5MB
setx SPRING_LOG_SECURITY_LEVEL DEBUG
setx SPRING_LOGIN_MAX_FAILED 5
setx SPRING_LOGIN_BLOCK_DURATION 30
setx SPRING_LOGIN_DELETE_LOG false
