@startuml
start

:Usuario ingresa datos de la suscripción (nombre, fecha de inicio, duración, etc.);
:Spring recibe los datos de la suscripción del usuario;

partition Validación {
  :Spring valida los datos de la suscripción;
  :Datos válidos?

  if (sí) then (yes)
    :Spring guarda la suscripción en la base de datos;
    :Spring notifica al usuario que la suscripción ha sido añadida correctamente;


  :Datos no válidos?
  :Spring notifica al usuario error de validación;
}

stop
@enduml
ml