@startuml

actor Usuario

Usuario --> (Registrarse)
Usuario --> (Iniciar sesión)
Usuario --> (Ver listado de gastos)
Usuario --> (Agregar nuevo gasto)
Usuario --> (Ver detalles de gasto)
Usuario --> (Agregar productos a gasto)
Usuario --> (Generar reporte de gastos)
Usuario --> (Ver historial de gastos)

(Ver listado de gastos) .up.> (Agregar nuevo gasto) : <<include>>
(Ver historial de gastos) .down.> (Ver listado de gastos) : <<include>>

@enduml
