@startuml
actor Usuario
actor Administrador
actor OCR
actor AI
actor Spring

' Casos de uso para el Usuario
Usuario --> (Registrarse)
Usuario --> (Iniciar sesión)
Usuario --> (Ver listado de gastos)
Usuario --> (Agregar nuevo gasto)
Usuario --> (Ver detalles de gasto)
Usuario --> (Agregar productos a gasto)
Usuario --> (Generar reporte de gastos)
Usuario --> (Ver historial de gastos)
Usuario --> (Acceder al chatbot)

' Casos de uso para el Administrador
Administrador --> (Ver listado de usuarios)
Administrador --> (Agregar/editar usuarios)
Administrador --> (Eliminar usuarios)
Administrador --> (Ver reportes de gastos)
Administrador --> (Generar reportes de gastos)
Administrador --> (Ver listado de gastos de todos los usuarios)

' Relación entre casos de uso
(Ver listado de gastos) .up.> (Agregar nuevo gasto) : <<include>>
(Ver historial de gastos) .down.> (Ver listado de gastos) : <<include>>

' Casos de uso para OCR
Spring --> (Enviar imagen al OCR)
OCR --> (Procesar imagen)
OCR --> (Enviar texto procesado a AI)
AI --> (Analizar datos)
AI --> (Devolver análisis a OCR)
OCR --> (Devolver texto procesado a Spring)

' Casos de uso para el chatbot
Usuario --> (Interactuar con el chatbot)
(Interactuar con el chatbot) .left.> (Acceder al chatbot) : <<include>>

@enduml
