@startuml
start

:Usuario ingresa el gasto\n(nombre, total, categoría, etc.);
:Spring recibe los datos del gasto del usuario;

partition Validación {
  :Spring valida los datos del gasto;

  if (Datos válidos?) then (sí)
    :Spring guarda el gasto en la base de datos;
    :Spring notifica al usuario\nque el gasto ha sido registrado;
    stop
  else (no)
    :Spring notifica al usuario\nerror de validación;
    stop
  endif
}

@enduml